name: ğŸ” merge checks
run-name: ğŸ” merge checks
on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  merge_check:
    name: ğŸ” merge checks
    runs-on: ubuntu-latest
    steps:
      - name: â¬ Check out repository code
        uses: actions/checkout@v4
      - name: â¬ Install stable rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: ğŸ›  Build ghdepup
        run: cargo build
      - name: ğŸ§ª Test ghdepup
        run: cargo test
      - name: ğŸ›  Build selfupdate
        run: cargo build
        working-directory: ./.github/actions/selfupdate
      - name: ğŸ§ª Test selfupdate
        run: cargo test
        working-directory: ./.github/actions/selfupdate
